# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 572b75e5a7d6d9e8e17d708c156380c9760a6153506431bfe30afe907184e606f1b2a6542d256e36fa6d578b6198838d4d76c3f40ce80b82c5550be4c307904d

test:
  secret_key_base: d41616a036bb235e142c1e28af2c5c6c8f5c9a089a50b656ef858e9b05d5736e9d0f89f0078fc09d55c4a0cb665628673c666c5a7d9329705f3ed22767b9624e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
